services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - wp-vol:/var/www/
    ports:
      - "443:443"
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - wp-vol:/var/www/
    networks:
      - default
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_AUTH_KEY: ${WP_AUTH_KEY}
      WP_SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
      WP_LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
      WP_NONCE_KEY: ${WP_NONCE_KEY}
      WP_AUTH_SALT: ${WP_AUTH_SALT}
      WP_SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      WP_LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
      WP_NONCE_SALT: ${WP_NONCE_SALT}

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - default
    environment:
      MARIADB_DATABASE: ${WP_DB_NAME}
      MARIADB_USER: ${WP_USER}
      MARIADB_PASSWORD: ${WP_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

networks:
  default:
    name: inception

volumes:
  db-vol:
    driver_opts:
      o: bind
      type: none
      device: ${MARIADB_VOLUME}

  wp-vol:
    driver_opts:
      o: bind
      type: none
      device: ${WORDPRESS_VOLUME}
