services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - wp-vol:/var/www/
    ports:
      - "443:443"
    networks:
      - default
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - wp-vol:/var/www/
    networks:
      - default
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    name: inception

volumes:
  db-vol:
    driver_opts:
      o: bind
      type: none
      device: ${MARIADB_VOLUME}

  wp-vol:
    driver_opts:
      o: bind
      type: none
      device: ${WORDPRESS_VOLUME}
